#!/usr/bin/env bash
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#

dotnet restore src/DoctorViewFhirInteractionApi/ && \
    dotnet build src/DoctorViewFhirInteractionApi/ && \
    echo "Now, run the following to start the project: dotnet run -p src/DoctorViewFhirInteractionApi/DoctorViewFhirInteractionApi.csproj --launch-profile web"
